import { sendEmail } from "./send_email";
import { db, auth, rtdb, storage, messaging } from "./firebase";
import { sendNotifications } from "./send_in_app_notifications";
import { getUserPermission } from "./get_user_permissions";
import { initialization } from "./init_data";
import { generateRandomString } from "./generate_random_string";
import { getFirstName } from "./get_forst_name";
import { getCurrency } from "./get_currency";
import { getRandom10DigitNumber } from "./random_10_digits";
import { round2SF } from "./round_2sf";
import { sendSMS } from "./send_sms";
import { getDateAndTime } from "./get_date_and_time";
import { getMessage } from "./messages";
import { savePDFs } from "./save_pdfs";
import { saveFiles } from "./save_files";
import { toProperCase } from "./to_proper_case";
import { sendOTP } from "./send_otp";
import { saveDocument } from "./save_document";
import azureClient from "./microsoft_azure";
import { generateSessionId } from "./generate_session_id";
import { getRandomUniqueCustomerNumber } from "./random_unique_number";
import { extractMatch } from "./extract_match";

